services:
  localstack:
    container_name: terraform-example
    image: localstack/localstack:3.8.1
    ports:
      - "4566:4566"
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"